name: PHP CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    phpunit:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.4'

            - name: Install dependencies
              run: |
                  composer install --no-interaction --prefer-dist

            - name: Run PHP CS Fixer
              run: |
                  composer run cs:chk

            - name: Run PHPStan
              run: |
                  composer run stan

            - name: Run PHPUnit tests
              run: |
                  composer run test

            - name: Generate code coverage report
              run: |
                  vendor/bin/phpunit --coverage-clover=coverage.xml

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              with:
                  files: coverage.xml
